/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.BillDao;
import Dao.RoomsDao;
import Dao.StudentDao;
import Model.BillModel;
import Model.RoomModel;
import Model.StudentModel;
import helper.DataValidator;
import helper.DatabaseHelper;
import helper.ImgaeHelper;
import helper.MessageDialogHelper;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author LoiDinh
 */
public class BillView extends javax.swing.JPanel {
private Page parentFrom;
private DefaultTableModel tblModel;
    /**
     * Creates new form BillView
     */
    public BillView() {
        initComponents();
        loadCMB();
        initTable();
        LoadDatatoTable();
        MouseHand();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBill = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIDStudent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbRoom = new javax.swing.JComboBox<>();
        ckStatus = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdParking = new javax.swing.JCheckBox();
        rdWash = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtPrice2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        kButton11 = new com.k33ptoo.components.KButton();
        BtnDelete = new com.k33ptoo.components.KButton();
        btnUpdate = new com.k33ptoo.components.KButton();
        TableBillInfo = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();
        txtFindByIDBill = new javax.swing.JTextField();
        kButton9 = new com.k33ptoo.components.KButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(683, 424));

        tableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBill.setRowHeight(25);
        tableBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBill);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biiling");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 22, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 86));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID STUDENT");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 66, -1, -1));

        txtIDStudent.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 120, 197)));
        txtIDStudent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDStudentFocusLost(evt);
            }
        });
        jPanel3.add(txtIDStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 82, 153, 30));

        jLabel4.setText("FULL NAME");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 130, -1, -1));

        txtFullName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 120, 197)));
        txtFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFullNameFocusLost(evt);
            }
        });
        jPanel3.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 150, 153, 30));

        jLabel5.setText("Room");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        cmbRoom.setBorder(null);
        cmbRoom.setOpaque(false);
        cmbRoom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbRoomFocusLost(evt);
            }
        });
        jPanel3.add(cmbRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 30));

        ckStatus.setBackground(new java.awt.Color(255, 255, 255));
        ckStatus.setText("Status");
        jPanel3.add(ckStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 240, 320));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197), 3));

        jLabel6.setText(" MONTH");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        cmbMonth.setBorder(null);
        cmbMonth.setOpaque(false);

        jLabel7.setText("PRICE");

        txtPrice1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 120, 197)));
        txtPrice1.setOpaque(false);
        txtPrice1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrice1FocusLost(evt);
            }
        });

        jLabel8.setText("Category");

        rdParking.setBackground(new java.awt.Color(255, 255, 255));
        rdParking.setText("Parking");

        rdWash.setBackground(new java.awt.Color(255, 255, 255));
        rdWash.setText("Wash");

        jLabel9.setText("PRICE");

        txtPrice2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 120, 197)));
        txtPrice2.setOpaque(false);

        jLabel10.setText("TOTAL");

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPrice.setText("0đ");
        txtTotalPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(71, 120, 197)));

        txtDate.setBackground(new java.awt.Color(255, 255, 255));
        txtDate.setOpaque(false);
        txtDate.setPreferredSize(new java.awt.Dimension(74, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMonth, 0, 160, Short.MAX_VALUE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(rdParking)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rdWash)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdParking)
                            .addComponent(rdWash)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(txtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 120, 197), 3));

        kButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_save_45px.png"))); // NOI18N
        kButton11.setkAllowGradient(false);
        kButton11.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });

        BtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_delete_trash_45px.png"))); // NOI18N
        BtnDelete.setkAllowGradient(false);
        BtnDelete.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_update_left_rotation_48px.png"))); // NOI18N
        btnUpdate.setkAllowGradient(false);
        btnUpdate.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        TableBillInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_list_50px.png"))); // NOI18N
        TableBillInfo.setkAllowGradient(false);
        TableBillInfo.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        TableBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableBillInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 370, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Bill: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        txtFindByIDBill.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(71, 120, 197)));
        txtFindByIDBill.setOpaque(false);
        jPanel1.add(txtFindByIDBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 70, 30));

        kButton9.setBackground(new java.awt.Color(243, 243, 243));
        kButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_search_contacts_20px.png"))); // NOI18N
        kButton9.setkAllowGradient(false);
        kButton9.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton9.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, 830, 460));
    }// </editor-fold>//GEN-END:initComponents
    private void LoadEmpty()
    {
        txtFindByIDBill.setText("");
        txtIDStudent.setText("");
        txtFullName.setText("");
        cmbMonth.setSelectedItem(null);
        cmbRoom.setSelectedItem(null);
        txtPrice1.setText("");
        rdParking.setSelected(false);
        rdWash.setSelected(false);
        txtPrice2.setText("");
    }
     private void MouseHand()
    {
    kButton11.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton9.setCursor(new Cursor(Cursor.HAND_CURSOR));
    BtnDelete.setCursor(new Cursor(Cursor.HAND_CURSOR));
    btnUpdate.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
     private  void initTable()
    {
        tblModel= new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"IDBill","ID Student","FullName","IDRoom","Month","Price1","Category","Price2","TotalPrice","Date"});
        tableBill.setModel(tblModel);
      
    }
     
     private void LoadDatatoTable()
    {
       try {
            BillDao dao= new BillDao();
           // List<BillModel> list=dao.FindByAll();
           List<BillModel> list= dao.FindByAll();
            tblModel.setRowCount(0);
            for(BillModel it:list)
            {
                tblModel.addRow(new Object[]{it.getIDBill(),
                it.getIDStdudent(),it.getFullName(),it.getIDRooms(),it.getMonth(),it.getPrice1(),it.getCategory(),it.getPrice2(),it.getTotalPrice(),it.getDate()
                
            });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentFrom, e.getMessage(), "Lỗi");
        }
    }
    private void loadCMB()
    {
//        int i=0;
        try {
            Connection con= DatabaseHelper.openConnection();
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(" select IDRooms from Rooms ");
            while(rs.next())
            {
//                i=1;
                cmbRoom.addItem(rs.getString("IDRooms"));
            }
            rs.close();
            con.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void txtFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFullNameFocusLost
        try {
            StudentDao dao= new StudentDao();
            StudentModel sv=dao.FindByID(Integer.valueOf(txtIDStudent.getText()));
            if(sv!=null)
            {
                txtFullName.setText(sv.getFullName());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtFullNameFocusLost

    private void txtPrice1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrice1FocusLost
        if(txtPrice1.getText().equals("")|| txtPrice2.getText().equals(""))
        {
            return;
        }
        float Price1= Float.parseFloat(txtPrice1.getText());
        float Price2= Float.parseFloat(txtPrice2.getText());
        
        
        float PriceTotal= Price1+Price2;
        String st=String.format("%.2f", PriceTotal);
        txtTotalPrice.setText(st);
        
    }//GEN-LAST:event_txtPrice1FocusLost
// tim kiem bill
    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        try {
            BillDao dao= new BillDao();
            BillModel bm= dao.FindByIDBill(Integer.parseInt(txtFindByIDBill.getText()));
            if(bm!=null)
            {
                txtIDStudent.setText(String.format("%d", bm.getIDStdudent()));
                txtFullName.setText(bm.getFullName());
                cmbRoom.setSelectedIndex(bm.getIDRooms());
                cmbMonth.setSelectedIndex(bm.getMonth());
                txtPrice1.setText(String.format("%d",bm.getPrice1()));
                txtPrice2.setText(String.format("%d",bm.getPrice2()));
                txtDate.setDate(bm.getDate()); 
//                ckStatus.setSelected(bm.getStatus());
            }else
            {
                MessageDialogHelper.showErrorDialog(parentFrom, "Không tìm thấy hoá đơn nào","Thông báo");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
             MessageDialogHelper.showErrorDialog(parentFrom, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
         StringBuilder sb= new StringBuilder();
        DataValidator.ValidationEmpty(txtIDStudent, sb, "Ma sinh vien khong duoc de trong");
        DataValidator.ValidationEmpty(txtPrice1, sb, "Enter The Price, Please");
        DataValidator.ValidationEmpty(txtPrice2, sb, "Enter The Price, Please");
        
        
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentFrom, sb.toString(), "Lỗi");
        }
        try {
            
            BillModel bm= new BillModel();
//            bm.setIDBill(Integer.parseInt(txtIDStudent.getText()));
            bm.setIDStdudent(Integer.parseInt(txtIDStudent.getText()));
            bm.setIDRooms(Integer.parseInt(txtIDStudent.getText()));
            bm.setFullName(txtFullName.getText());
            bm.setIDRooms(Integer.parseInt((String)cmbRoom.getSelectedItem().toString()));
            bm.setMonth(Integer.parseInt((String)cmbMonth.getSelectedItem().toString()));
            bm.setPrice1(Integer.parseInt(txtPrice1.getText()));
            bm.setPrice2(Integer.parseInt(txtPrice2.getText()));
            bm.setTotalPrice((int) Float.parseFloat(txtTotalPrice.getText()));
            bm.setDate(txtDate.getDate());
            bm.setStatus(ckStatus.isSelected());

            
            if(rdParking.isSelected())
            {
                bm.setCategory(rdParking.getText());
            }
            if(rdWash.isSelected())
            {
                bm.setCategory(rdWash.getText());
            }
            if(rdParking.isSelected()&&rdWash.isSelected())
            {
                bm.setCategory("2");
            }
//            bm.setCategory(rdParking.getText());
            RoomModel rm= new RoomModel();
            rm.setIDRooms(Integer.parseInt((String)cmbRoom.getSelectedItem().toString()));
            BillDao dao= new BillDao();
            if(dao.insert(bm))
            {
                if(ckStatus.isSelected())
                {
                    if(dao.updateCheckRoom(rm))
                    {
                        
                    }
                    else
                    {
                         MessageDialogHelper.showMessageDialog(parentFrom, "Sinh viên chưa được thêm vào phòng", "Thông báo");
                    }
                }
                MessageDialogHelper.showMessageDialog(parentFrom, "Hoá đơn đã được lưu", "Thông báo");
                
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentFrom, "Hoá đơn chưa được lưu", TOOL_TIP_TEXT_KEY);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentFrom, e.getMessage(), " Lỗi");
        }
    }//GEN-LAST:event_kButton11ActionPerformed

    private void cmbRoomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbRoomFocusLost
            // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomFocusLost

    private void txtIDStudentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDStudentFocusLost
        try {
            StudentDao dao= new StudentDao();
            StudentModel sm= dao.FindByID(Integer.parseInt(txtIDStudent.getText()));
            if(sm!=null)
            {
                txtFullName.setText(sm.getFullName());
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtIDStudentFocusLost

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        StringBuilder sb= new StringBuilder();
        DataValidator.ValidationEmpty(txtFindByIDBill, sb, "Ma sinh vien khong duoc de trong");
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentFrom, sb.toString(), "Lỗi");
        }
        if(MessageDialogHelper.showConfirmDialog(parentFrom, "Bạn có muốn xoá hoá đơn này không ", "Thông báo quan trọng")==JOptionPane.NO_OPTION){
             
            return;
            
        }
        try {
           
            BillDao dao= new BillDao();
            if(dao.delete(Integer.parseInt(txtFindByIDBill.getText())))
            {
                MessageDialogHelper.showMessageDialog(parentFrom, "Hoá đơn đã được xoá", "Thông báo");
                
            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentFrom, "Hoá đơn chưa được xoá", TOOL_TIP_TEXT_KEY);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentFrom, e.getMessage(), " Lỗi");
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        StringBuilder sb= new StringBuilder();
        DataValidator.ValidationEmpty(txtIDStudent, sb, "Ma sinh vien khong duoc de trong");
        DataValidator.ValidationEmpty(txtPrice1, sb, "Enter The Price, Please");
        DataValidator.ValidationEmpty(txtPrice2, sb, "Enter The Price, Please");
        
        
        if(sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(parentFrom, sb.toString(), "Lỗi");
        }
        try {
            BillModel bm= new BillModel();
            bm.setIDBill(Integer.parseInt(txtFindByIDBill.getText()));
//            bm.setIDBill(Integer.parseInt(txtIDStudent.getText()));
            bm.setIDStdudent(Integer.parseInt(txtIDStudent.getText()));
            bm.setIDRooms(Integer.parseInt(txtIDStudent.getText()));
            bm.setFullName(txtFullName.getText());
            bm.setIDRooms(Integer.parseInt((String)cmbRoom.getSelectedItem()));
            bm.setMonth(Integer.parseInt((String)cmbMonth.getSelectedItem()));
            

            
            bm.setPrice1(Integer.parseInt(txtPrice1.getText()));
            bm.setPrice2(Integer.parseInt(txtPrice2.getText()));
            bm.setTotalPrice((int) Float.parseFloat(txtTotalPrice.getText()));
//            bm.setDate(txtDate.getDate());
            bm.setStatus(ckStatus.isSelected());
            if(rdParking.isSelected())
            {
                bm.setCategory(rdParking.getText());
            }
            if(rdWash.isSelected())
            {
                bm.setCategory(rdWash.getText());
            }
            if(rdParking.isSelected()&&rdWash.isSelected())
            {
                bm.setCategory("2");
            }
            BillDao dao= new BillDao();
            if(dao.update(bm))
            {
                MessageDialogHelper.showMessageDialog(parentFrom, "Sinh viên đã được lưu", "Thông báo");
                LoadEmpty();
                

            }
            else
            {
                MessageDialogHelper.showConfirmDialog(parentFrom, "Sinh viên chưa được lưu", TOOL_TIP_TEXT_KEY);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentFrom, e.getMessage(), " Lỗi");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void TableBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableBillInfoActionPerformed
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);
        LoadDatatoTable();
    }//GEN-LAST:event_TableBillInfoActionPerformed
// load tabe 
    private void tableBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBillMouseClicked
                                         

    }//GEN-LAST:event_tableBillMouseClicked
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton BtnDelete;
    private com.k33ptoo.components.KButton TableBillInfo;
    private com.k33ptoo.components.KButton btnUpdate;
    private javax.swing.JCheckBox ckStatus;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbRoom;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton9;
    private javax.swing.JCheckBox rdParking;
    private javax.swing.JCheckBox rdWash;
    public javax.swing.JTable tableBill;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtFindByIDBill;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtIDStudent;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtPrice2;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
