/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;

/**
 *
 * @author LoiDinh
 */
public class HomeView extends javax.swing.JPanel {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
        MouseHand();
    }
private void MouseHand()
{
    kButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton5.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton6.setCursor(new Cursor(Cursor.HAND_CURSOR));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();

        setBackground(new java.awt.Color(243, 243, 243));

        jPanel1.setBackground(new java.awt.Color(243, 243, 243));

        kButton1.setText("STUDENT");
        kButton1.setkAllowGradient(false);
        kButton1.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton1.setkHoverColor(new java.awt.Color(39, 59, 81));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 0));

        kButton2.setText("CREATE ROOM");
        kButton2.setkAllowGradient(false);
        kButton2.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton2.setkHoverColor(new java.awt.Color(39, 59, 81));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 0));

        kButton3.setText("BILL");
        kButton3.setkAllowGradient(false);
        kButton3.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton3.setkHoverColor(new java.awt.Color(39, 59, 81));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 0));

        kButton4.setText("STATISTICAL");
        kButton4.setkAllowGradient(false);
        kButton4.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton4.setkHoverColor(new java.awt.Color(39, 59, 81));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 0));

        kButton5.setText("EXIT");
        kButton5.setkAllowGradient(false);
        kButton5.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton5.setkHoverColor(new java.awt.Color(39, 59, 81));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 0));

        kButton6.setText("CHANGE ACCOUNT");
        kButton6.setkAllowGradient(false);
        kButton6.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton6.setkHoverColor(new java.awt.Color(39, 59, 81));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(kButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(kButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(kButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    // End of variables declaration//GEN-END:variables
}
