/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import helper.ShareData;
import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author LoiDinh
 */
public class Page extends javax.swing.JFrame {
private JPanel childPanel;
   
    /**
     * Creates new form Page
     */
    public Page() {
        initComponents();
        setLocationRelativeTo(null);
//        setExtendedState(getExtendedState()| JFrame.MAXIMIZED_BOTH);
         this.openWelcome();
        setResizable(false);
        LoginDiaLog diaLog= new LoginDiaLog(this,true);
        diaLog.setVisible(true);
        processLogin();
        setdate();
        MouseHand();
       setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    
        

    }
    void openWelcome() {
        new ProcessBar(this, true).setVisible(true);
    }
    Student hs;
    public void reloadPanel(int i){
         jpnLayout.removeAll();
        switch (i) {
            case 1:
                if (hs == null) {
                    hs = new Student();
                } 
               
                jpnLayout.add(hs);
                break;
//            case 2:
//                if (home == null) {
//                    home = new JpHome();
//                }
//                btnTrangChu.setPressedIcon(new ImageIcon("down.png"));
//                mp3 = new MP3 ("src/Sound/kasya.MP3");
//                mp3.play();
//                jpLayout.add(home);
//                break;
            default:
                break;
        }
        jpnLayout.updateUI();
    }
     public void setdate()
    {
        ActionListener actiondate= new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                java.util.Date  mydate= new Date();
//                lbldateCity.setText(mydate.getDay()+"/"+ mydate.getMonth()+"/"+mydate.getYear());
                llblTimezone.setText(mydate.getHours()+" : "+ mydate.getMinutes()+" : "+mydate.getSeconds());
            }
            
        };
        new javax.swing.Timer(1000,actiondate).start();
    }
     private void loadJPanel(JPanel newPanel) {
        jpnLayout.removeAll();
        jpnLayout.add(newPanel);
        jpnLayout.updateUI();
    }
    private void processLogin()
    {
       jLabel2.setText(ShareData.nguoidangnhap.getUserName());
       jLabel3.setText(ShareData.nguoidangnhap.getRole());
       
       if(ShareData.nguoidangnhap.getRole().equals("Staff"))
       {
           kButton7.setEnabled(false);
       }
    }
    private void MouseHand()
{
    kButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton5.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton6.setCursor(new Cursor(Cursor.HAND_CURSOR));
    kButton7.setCursor(new Cursor(Cursor.HAND_CURSOR));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        llblTimezone = new javax.swing.JLabel();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton8 = new com.k33ptoo.components.KButton();
        jpnLayout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(58, 100, 166));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(58, 100, 166));
        jPanel4.setFocusTraversalPolicyProvider(true);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hi Admin");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User");

        llblTimezone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        llblTimezone.setForeground(new java.awt.Color(255, 255, 255));
        llblTimezone.setText("Time");

        kButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_home_50px.png"))); // NOI18N
        kButton5.setkAllowGradient(false);
        kButton5.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton5.setkHoverColor(new java.awt.Color(58, 100, 166));
        kButton5.setkPressedColor(new java.awt.Color(58, 100, 166));
        kButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton5MouseClicked(evt);
            }
        });
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(llblTimezone))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(llblTimezone)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        kButton1.setBackground(new java.awt.Color(224, 223, 225));
        kButton1.setText("ROOM_INFO");
        kButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kButton1.setkAllowGradient(false);
        kButton1.setkAllowTab(true);
        kButton1.setkBackGroundColor(new java.awt.Color(51, 78, 108));
        kButton1.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton1.setkHoverColor(new java.awt.Color(27, 44, 63));
        kButton1.setkSelectedColor(new java.awt.Color(102, 102, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, 244, -1));

        kButton2.setText("STUDENTS");
        kButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kButton2.setkAllowGradient(false);
        kButton2.setkAllowTab(true);
        kButton2.setkBackGroundColor(new java.awt.Color(51, 78, 108));
        kButton2.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton2.setkHoverColor(new java.awt.Color(27, 44, 63));
        kButton2.setkSelectedColor(new java.awt.Color(102, 102, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 337, 244, -1));

        kButton3.setBackground(new java.awt.Color(54, 33, 89));
        kButton3.setText("ROOMS");
        kButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kButton3.setkAllowGradient(false);
        kButton3.setkAllowTab(true);
        kButton3.setkBackGroundColor(new java.awt.Color(51, 78, 108));
        kButton3.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverColor(new java.awt.Color(27, 44, 63));
        kButton3.setkSelectedColor(new java.awt.Color(102, 102, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 216, 244, -1));

        kButton4.setText("STATISTICAL");
        kButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kButton4.setkAllowGradient(false);
        kButton4.setkAllowTab(true);
        kButton4.setkBackGroundColor(new java.awt.Color(51, 78, 108));
        kButton4.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton4.setkHoverColor(new java.awt.Color(27, 44, 63));
        kButton4.setkSelectedColor(new java.awt.Color(102, 102, 255));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 244, -1));

        kButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_exit_50px.png"))); // NOI18N
        kButton6.setkEndColor(new java.awt.Color(58, 100, 166));
        kButton6.setkHoverColor(new java.awt.Color(58, 100, 166));
        kButton6.setkHoverEndColor(new java.awt.Color(58, 100, 166));
        kButton6.setkHoverForeGround(new java.awt.Color(58, 100, 166));
        kButton6.setkHoverStartColor(new java.awt.Color(58, 100, 166));
        kButton6.setkPressedColor(new java.awt.Color(58, 100, 166));
        kButton6.setkStartColor(new java.awt.Color(58, 100, 166));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 60, 70));

        kButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagev2/icons8_male_user_48px.png"))); // NOI18N
        kButton7.setkAllowGradient(false);
        kButton7.setkBackGroundColor(new java.awt.Color(58, 100, 166));
        kButton7.setkEndColor(new java.awt.Color(58, 100, 166));
        kButton7.setkForeGround(new java.awt.Color(58, 100, 166));
        kButton7.setkHoverColor(new java.awt.Color(58, 100, 166));
        kButton7.setkHoverEndColor(new java.awt.Color(58, 100, 166));
        kButton7.setkHoverForeGround(new java.awt.Color(58, 100, 166));
        kButton7.setkHoverStartColor(new java.awt.Color(58, 100, 166));
        kButton7.setkPressedColor(new java.awt.Color(58, 100, 166));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 60, 70));

        kButton8.setText("BILLS");
        kButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kButton8.setkAllowGradient(false);
        kButton8.setkAllowTab(true);
        kButton8.setkBackGroundColor(new java.awt.Color(51, 78, 108));
        kButton8.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton8.setkHoverColor(new java.awt.Color(27, 44, 63));
        kButton8.setkSelectedColor(new java.awt.Color(102, 102, 255));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 393, 244, -1));

        jpnLayout.setBackground(new java.awt.Color(255, 255, 255));
        jpnLayout.setLayout(new javax.swing.BoxLayout(jpnLayout, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        loadJPanel(new Student());
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        loadJPanel(new RoomsView());
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
       loadJPanel(new RoomInfoView());
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        loadJPanel(new StatisticalView());
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton5MouseClicked

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        loadJPanel(new HomeView());
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        LoginDiaLog diaLog= new LoginDiaLog(this,true);
        
        diaLog.setVisible(true);
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
       RegisterDialog lg= new RegisterDialog(this,true);
       
       lg.setVisible(true);
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        loadJPanel(new BillView());
    }//GEN-LAST:event_kButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpnLayout;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private javax.swing.JLabel llblTimezone;
    // End of variables declaration//GEN-END:variables
}
